### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by madbananas**
Fixed "interface" double references

### CODE REVIEW

**Comment by pespin** [comment]
Thanks for contributing, but patches must go into https://gerrit.osmocom.org, not here.

**Comment by pespin** [comment]
See following wiki page on how to contribute: https://osmocom.org/projects/cellular-infrastructure/wiki/Gerrit

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please read the following instructions to [submit patches](http://osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Pull request closed without merging**
